# Generated by Django 4.1.2 on 2024-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermentator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='odpoved',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='pozdrav',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=155.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=155.0),
        ),
    ]
