# Generated by Django 4.1.2 on 2024-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermentator', '0002_remove_sensordata_odpoved_remove_sensordata_pozdrav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='desired_temp',
            field=models.FloatField(default=155.0),
        ),
    ]
