# Generated by Django 4.1.2 on 2025-03-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fermentator', '0004_fermentbatch_sensordata_ferment_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='ferment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_data', to='fermentator.fermentbatch'),
        ),
    ]
