version: '3.9'

services:
  django:
    build:
      context: .
    volumes:
      - .:/app
      - static_data:/app/static
      - media_data:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_URL=postgres://user:password@db:5432/dbname

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/static
      - media_data:/media
    depends_on:
      - django

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./entrypoint.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  static_data:
  media_data:
  pgadmin_data:
