name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm64 -t smeglofus/home_app:latest ./home_app --push

      - name: Deploy on Raspberry Pi
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RASPBERRY_PI_IP }}  # ujistěte se, že je zde správný formát
          username: ${{ secrets.RASPBERRY_PI_USER }}
          password: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          script: |
            sudo systemctl status ssh
            docker info  # Ověřte, že Docker je spuštěn
            docker pull smeglofus/home_app:latest
            docker-compose down
            docker-compose up -d
