name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy on Raspberry Pi
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RASPBERRY_PI_IP }}
          username: ${{ secrets.RASPBERRY_PI_USER }}
          password: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          script: |
            # Navigate to your project directory
            cd /homeapp/homeServerApp

            # Pull the latest changes
            git pull origin main # Make sure this matches the branch you're pushing to

            # Build the Docker image
            docker build -t smeglofus/home_app:latest .

            # Restart the application using Docker Compose
            docker-compose down
            docker-compose up -d
